version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: langapp-db
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: mydatabase
    env_file:
      - .env
    volumes:
      - maron_speak_data:/var/lib/postgresql/data
      - ./internal/repository/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9432:5432"

volumes:
  maron_speak_data:
